# -*- coding: utf-8 -*-
from __future__ import annotations


RULE_NAME_FALLBACK_CN = {
    "day_night_link_w1": "晚自习需当天下午有课",
    "day_night_link_night_requires_day": "白天无课不得安排晚自习/晚查寝",
    "day_night_link_sun_night_no_mon_am1": "周日晚自习=>周一上午1禁排",
    "day_night_link_sun_pm_night_no_mon_am": "周日白天+晚自习后周一上午禁排",
    "day_night_link_w3": "有晚自习=>次日尽量不排上午1",
    "day_night_link_w4": "白天负荷重=>当晚尽量不排晚自习",
    "day_night_link_two_class_empty_day_no_night": "双班教师空整天=>当晚尽量不排晚自习",
    "lang_pm_penalty": "语文/外语下午惩罚",
    "lang_tue_fri_am1_reward": "语文外语周二至周五上午1奖励",
    "lang_tue_fri_pm1_penalty": "语文外语周二至周五下午1惩罚",
    "lang_tue_fri_pm2_penalty": "语文外语周二至周五下午2惩罚",
    "lang_tue_fri_pm3_penalty": "语文外语周二至周五下午3惩罚",
    "multi_class_halfday_split": "多班教师半天拆分",
}


PERSONALIZED_RULE_NAME_CN = {
    "rule1": "指定教师：有下午3时晚自习尽量不排",
    "rule28_xhd_night_no_pm": "指定教师：晚自习当天下午不排课",
    "rule2_diff": "指定教师/指定教师：晚自习日期尽量重合（差异惩罚）",
    "rule2_overlap": "指定教师/指定教师：整周至少同天一次晚自习",
    "rule2_couple_overlap_soft": "指定教师/指定教师：整周至少同天一次晚自习",
    "rule3": "指定教师：晚自习需当日有白天下午课",
    "rule4": "指定教师：周日尽量上午1+2",
    "rule5_am": "指定教师：周日偏好上午",
    "rule5_night": "指定教师：周日晚自习尽量不排",
    "rule7_cnt": "政治：周日晚自习教师人数控制",
    "rule7_super": "政治：周日晚自习超限高罚",
    "rule8": "指定教师：尽量减少下午课",
    "rule32_ld_tue_fri_pm_each": "指定教师：周二至周五下午每节课惩罚",
    "rule33_ld_tue_fri_pm1_extra_each": "指定教师：周二至周五下午1额外惩罚",
    "rule10_mon_am1": "指定教师：周一上午1尽量不排",
    "rule10_sun_pm": "指定教师：周日下午偏好",
    "rule10_sun_night": "指定教师：周日晚自习尽量不排",
    "rule11_sun_am": "指定教师：周日上午偏好",
    "rule11_outside": "指定教师：晚自习尽量安排在周日/周一",
    "rule11_need": "指定教师：需至少周日或周一晚自习",
    "rule30_csqi_consecutive_night": "指定教师：晚自习需连续两天",
    "rule12_sun_night": "指定教师：周日晚自习尽量不排",
    "rule12_sun_am": "指定教师：周日上午偏好",
    "rule12_am4": "指定教师：尽量减少上午4",
    "rule34_zzx_no_sunday_night": "指定教师：周日晚自习禁排",
    "rule38_xyx_night_days_only": "指定教师：晚自习仅允许指定日期",
    "rule13_need": "指定教师：晚自习偏好周日/周一",
    "rule13_consec": "指定教师：晚自习偏好连续两天",
    "rule13_hwj_sun_mon_assign": "指定教师：晚自习安排在周日与周一",
    "rule14": "指定教师：周五晚自习尽量不排",
    "rule35_hsm_weekday_early_no_am1": "指定教师：工作日有早自习则不排上午1",
    "rule36_wxl_weekday_early_no_am1": "指定教师：工作日有早自习则不排上午1",
    "rule15_am1": "指定教师：周一至周五上午1惩罚",
    "rule16_zfj_night_checkin_penalty": "指定教师：晚查寝惩罚",
    "rule17_xww_am4_pm1": "指定教师：工作日AM4+PM1阶梯惩罚",
    "rule18_zfy_consecutive_night": "指定教师：不连续两天晚自习",
    "rule29_zw_no_consecutive_night": "指定教师：晚自习不连续",
    "rule19_zfy_no_sunday_night": "指定教师：周日晚自习禁排",
    "rule20_sll_sun_am_only": "指定教师：周日只排上午",
    "rule21_cc_weekday_no_am4": "指定教师：周一至周五不排上午4",
    "rule22_cc_sat_am34_class17": "指定教师：周六上午3/4若排课则排17班",
    "rule23_sm_mon_no_am": "指定教师：周一上午不排课",
    "rule24_sm_mon_no_pm1": "指定教师：周一下午1不排课",
    "rule25_zw_am1_cap": "指定教师：上午1周累计最多1节",
    "rule26_zw_am2_cap": "指定教师：上午2周累计最多2节",
    "rule27_zw_am4_cap": "指定教师：上午4周累计最多1节",
    "rule37_zw_weekday_pm1_cap": "指定教师：周一至周五下午1最多2节",
    "rule39_dln_weekday_no_am1": "指定教师：周一至周五不排上午1",
    "rule31_mrj_hsm_sun_am12_fixed": "指定教师/指定教师：周日固定上午1+2",
}


PERSONALIZED_RULE_DESC_CN = {
    "rule1": "指定教师在当天下午3有课时，晚自习尽量不安排。",
    "rule28_xhd_night_no_pm": "指定教师若当晚有晚自习，当天下午应不排课。",
    "rule2_diff": "指定教师与指定教师晚自习日期差异越大，罚分越高。",
    "rule2_overlap": "指定教师与指定教师整周至少要有1天同天晚自习。",
    "rule2_couple_overlap_soft": "指定教师与指定教师整周至少要有1天同天晚自习。",
    "rule3": "指定教师有晚自习时，要求当天下午有白天课。",
    "rule4": "指定教师周日尽量安排上午1和上午2。",
    "rule5_am": "鼓励指定教师周日白天排在上午时段。",
    "rule5_night": "鼓励指定教师周日晚自习不排课。",
    "rule7_cnt": "控制政治教师在周日晚自习的上课人数。",
    "rule7_super": "政治教师周日晚人数超限时追加高额罚分。",
    "rule8": "指定教师白天下午课尽量减少。",
    "rule32_ld_tue_fri_pm_each": "指定教师在周二至周五安排下午课时，每节课产生一次罚分。",
    "rule33_ld_tue_fri_pm1_extra_each": "指定教师在周二至周五安排下午1时，在下午课罚分基础上追加罚分。",
    "rule10_mon_am1": "指定教师周一上午1尽量不排课。",
    "rule10_sun_pm": "鼓励指定教师周日下午排课。",
    "rule10_sun_night": "鼓励指定教师周日晚自习不排课。",
    "rule11_sun_am": "鼓励指定教师周日白天安排在上午。",
    "rule11_outside": "指定教师晚自习尽量安排在周日/周一，其他日期会罚分。",
    "rule11_need": "指定教师至少需要周日或周一安排一次晚自习。",
    "rule30_csqi_consecutive_night": "指定教师晚自习需至少形成一组连续两天（含周日→周一）。",
    "rule12_sun_night": "鼓励指定教师周日晚自习不排课。",
    "rule12_sun_am": "鼓励指定教师周日白天安排在上午。",
    "rule12_am4": "指定教师上午4排课次数尽量减少。",
    "rule34_zzx_no_sunday_night": "指定教师周日晚自习禁排，支持软硬切换。",
    "rule38_xyx_night_days_only": "指定教师晚自习仅允许安排在配置的日期集合内（默认星期五/星期日）。",
    "rule13_need": "指定教师晚自习优先安排在周日与周一。",
    "rule13_consec": "指定教师若有多次晚自习，鼓励安排在连续两天。",
    "rule13_hwj_sun_mon_assign": "指定教师晚自习应安排在周日与周一。",
    "rule14": "指定教师周五晚自习尽量不排课。",
    "rule35_hsm_weekday_early_no_am1": "指定教师在周一到周五若当天有早自习，则上午1不应再排课。",
    "rule36_wxl_weekday_early_no_am1": "指定教师在周一到周五若当天有早自习，则上午1不应再排课。",
    "rule15_am1": "指定教师在周一到周五上午1排课会产生惩罚。",
    "rule16_zfj_night_checkin_penalty": "指定教师每被安排1次晚查寝即触发一次罚分。",
    "rule17_xww_am4_pm1": "指定教师工作日 AM4+PM1 次数超过阈值按阶梯罚分。",
    "rule18_zfy_consecutive_night": "指定教师晚自习不应连续两天（含周日→周一）。",
    "rule29_zw_no_consecutive_night": "指定教师晚自习不应连续两天（含周日→周一）。",
    "rule19_zfy_no_sunday_night": "指定教师周日晚自习禁排。",
    "rule20_sll_sun_am_only": "指定教师周日白天只排上午，下午排课会罚分。",
    "rule21_cc_weekday_no_am4": "指定教师周一到周五不排上午4。",
    "rule22_cc_sat_am34_class17": "指定教师周六上午3/4若排课，要求安排在17班。",
    "rule23_sm_mon_no_am": "指定教师周一上午不排课。",
    "rule24_sm_mon_no_pm1": "指定教师周一下午1不排课。",
    "rule25_zw_am1_cap": "指定教师上午1周累计不超过上限。",
    "rule26_zw_am2_cap": "指定教师上午2周累计不超过上限。",
    "rule27_zw_am4_cap": "指定教师上午4周累计不超过上限。",
    "rule37_zw_weekday_pm1_cap": "指定教师在周一到周五的下午1周累计不超过上限。",
    "rule39_dln_weekday_no_am1": "指定教师在周一到周五不应安排上午1。",
    "rule31_mrj_hsm_sun_am12_fixed": "指定教师、指定教师周日白天课程应固定在上午1和上午2。",
}


PERSONALIZED_RULE_TEACHERS = {
    "rule1": "指定教师",
    "rule28_xhd_night_no_pm": "指定教师",
    "rule2_diff": "指定教师,指定教师",
    "rule2_overlap": "指定教师,指定教师",
    "rule2_couple_overlap_soft": "指定教师,指定教师",
    "rule3": "指定教师",
    "rule4": "指定教师",
    "rule5_am": "指定教师",
    "rule5_night": "指定教师",
    "rule8": "指定教师",
    "rule32_ld_tue_fri_pm_each": "指定教师",
    "rule33_ld_tue_fri_pm1_extra_each": "指定教师",
    "rule10_mon_am1": "指定教师",
    "rule10_sun_pm": "指定教师",
    "rule10_sun_night": "指定教师",
    "rule11_sun_am": "指定教师",
    "rule11_outside": "指定教师",
    "rule11_need": "指定教师",
    "rule30_csqi_consecutive_night": "指定教师",
    "rule12_sun_night": "指定教师",
    "rule12_sun_am": "指定教师",
    "rule12_am4": "指定教师",
    "rule34_zzx_no_sunday_night": "指定教师",
    "rule38_xyx_night_days_only": "指定教师",
    "rule13_need": "指定教师",
    "rule13_consec": "指定教师",
    "rule13_hwj_sun_mon_assign": "指定教师",
    "rule14": "指定教师",
    "rule35_hsm_weekday_early_no_am1": "指定教师",
    "rule36_wxl_weekday_early_no_am1": "指定教师",
    "rule15_am1": "指定教师",
    "rule16_zfj_night_checkin_penalty": "指定教师",
    "rule17_xww_am4_pm1": "指定教师",
    "rule18_zfy_consecutive_night": "指定教师",
    "rule29_zw_no_consecutive_night": "指定教师",
    "rule19_zfy_no_sunday_night": "指定教师",
    "rule20_sll_sun_am_only": "指定教师",
    "rule21_cc_weekday_no_am4": "指定教师",
    "rule22_cc_sat_am34_class17": "指定教师",
    "rule23_sm_mon_no_am": "指定教师",
    "rule24_sm_mon_no_pm1": "指定教师",
    "rule25_zw_am1_cap": "指定教师",
    "rule26_zw_am2_cap": "指定教师",
    "rule27_zw_am4_cap": "指定教师",
    "rule37_zw_weekday_pm1_cap": "指定教师",
    "rule39_dln_weekday_no_am1": "指定教师",
    "rule31_mrj_hsm_sun_am12_fixed": "指定教师,指定教师",
}


DORM_RULE_NAME_FALLBACK = {
    "night_checkin_zeng_need_on": "指定教师晚查寝需当日有晚自习",
    "noon_dorm_ban_lihuijiao_soft": "中午查寝禁止指定教师（软约束）",
    "noon_dorm_ban_zeng_soft": "中午查寝禁止指定教师（软约束）",
    "noon_dorm_need_am4_lvl3": "中午查寝优先上午4（上午3替代）",
    "noon_dorm_need_am4_lvl2": "中午查寝优先上午4（上午2替代）",
    "noon_dorm_need_am4_lvl1": "中午查寝优先上午4（上午1替代）",
    "noon_dorm_need_am4_lvl0": "中午查寝优先上午4（当日无上午课）",
    "noon_dorm_avoid_pm1": "中午查寝当天尽量不排下午1",
    "noon_female_with_night_checkin": "女教师同日中午查寝+晚查寝惩罚",
    "night_checkin_repeat_male": "晚查寝重复惩罚（男）",
    "night_checkin_repeat_female": "晚查寝重复惩罚（女）",
}
